{
    "name": "Wiqaya Physiotherapy Management",
    "version": "19.0.5.0.0",
    "summary": "Physiotherapy clinic operations, care plans, and billing",
    "category": "Healthcare",
    "author": "Wiqaya Clinic Team",
    "license": "LGPL-3",
    "pre_init_hook": "pre_init_hook",
    "depends": ["base", "mail", "contacts", "calendar", "product", "account"],
    "assets": {
        "web.assets_backend": [
            "pt_clinic/static/src/css/wiqaya_dashboard.css",
        ],
    },
    "data": [
        "security/pt_clinic_security.xml",
        "security/ir.model.access.csv",
        "security/pt_clinic_rules.xml",
        "data/pt_sequence.xml",
        "data/pt_defaults.xml",
        "data/pt_cron.xml",
        "data/pt_branding.xml",
        "views/report_templates.xml",
        "views/dashboard_views.xml",
        "views/branch_views.xml",
        "views/patient_views.xml",
        "views/appointment_views.xml",
        "views/treatment_views.xml",
        "views/billing_views.xml",
        "views/settings_views.xml",
        "views/report_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
